# FaxCloud Analyzer iOS - Podfile
# CocoaPods dependency management

platform :ios, '14.0'

target 'FaxCloudAnalyzer' do
  use_frameworks!

  # UI & Layout
  pod 'SnapKit', '~> 5.6.0'
  
  # Networking
  pod 'Alamofire', '~> 5.9'
  
  # JSON Parsing
  pod 'SwiftyJSON', '~> 5.0'
  
  # Local Storage
  pod 'RealmSwift', '~> 10.43'
  
  # Security
  pod 'KeychainAccess', '~> 4.2'
  
  # Analytics & Logging
  pod 'FirebaseAnalytics', '~> 10.0'
  pod 'FirebaseCrashlytics', '~> 10.0'
  
  # Date handling
  pod 'DateToolsSwift', '~> 5.2'
  
  # Development pods
  target 'FaxCloudAnalyzerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'COCOAPODS=1',
      ]
    end
  end
end
