[general]
; Modules requis pour la détection fax
autoload = yes

[modules]
load = res_fax.so
load = res_fax_spandsp.so
load = app_fax.so
load = app_dial.so
load = chan_pjsip.so
load = res_pjsip.so
load = res_pjsip_session.so
load = manager.so
